name: CI/CD Breast Cancer API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python app/test_api.py

      - name: Build Docker image
        run: docker build -t breast-cancer-api .

      - name: Save Docker image as tar
        run: |
          mkdir -p package
          docker save breast-cancer-api:latest -o package/breast-cancer-api.tar

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag Docker image for DockerHub
        run: docker tag breast-cancer-api ${{ secrets.DOCKERHUB_USERNAME }}/breast-cancer-api:latest

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/breast-cancer-api:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: breast-cancer-api-image
          path: package/breast-cancer-api.tar